version: 2

jobs:
  build-and-test:
    docker:
            - image: alpine
    steps:
        - checkout
        - run:
            name: Echo Test
            command: echo "CircleCI Test"
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: sudo pip install awscli
      - run:
          name: SSH経由のデプロイ
          command: |
            ./shells/deploy.sh

workflows:
  version: 2
  workflows:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
